### ISSUE TITLE
insights createsuperuser

### ISSUE THREAD

**Issue by zhaodagang** [mariusandra/insights#10]
PS F:\insights\node_modules> insights createsuperuser
module.js:549
    throw err;
    ^

Error: Cannot find module 'F:\insights\node_modules\insights-createsuperuser'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by zhaodagang** [comment]
my system is window
